# Generated by Django 5.1.7 on 2025-03-31 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-submitted_at'], 'permissions': [('can_export_messages', 'Can export contact messages')], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_responded',
            field=models.BooleanField(default=False, verbose_name='Responded Status'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='response_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Response'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='A valid email address', max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='Your message (10-2000 characters)', max_length=2000, validators=[django.core.validators.MinLengthValidator(10, 'Message must be at least 10 characters')], verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Your full name', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submission Date'),
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='contact_messages',
        ),
    ]
